version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test

  deploy-job:
    docker:
      - image: circleci/node:7.10
    working_directory: /tmp/  
    steps:
      - run:
          name: download convox CLI
          command: curl -Ls https://convox.com/install/linux.zip > /tmp/convox.zip
      - run:
          name: install Convox CLI
          command: sudo unzip /tmp/convox.zip -d /usr/local/bin
      - run:
          name: Deploy via Convox
          command: convox deploy --app player --rack dotpodcast/dotpodcast

workflows:
  version: 2
  build-deploy-master:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: develop

